// Python FSE/Deepskilling/Frontend Development/handson_8/task3/src/components/Header.vue
<script setup>

import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<template>

<header>

<h1>Student Portal</h1>

<nav>

<RouterLink to="/">Home</RouterLink>

<RouterLink to="/courses">Courses</RouterLink>

<RouterLink to="/profile">Profile</RouterLink>

</nav>

<div>

Enrolled : {{ store.enrolledCourses.length }}

</div>

</header>

</template>

<style scoped>

header{

display:flex;
justify-content:space-between;
align-items:center;
padding:20px;
background:#2c3e50;
color:white;

}

nav a{

color:white;
margin-left:20px;
text-decoration:none;

}

</style>

// Python FSE/Deepskilling/Frontend Development/handson_6/task2/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useContext } from "react";
import { EnrollmentContext } from "../context/EnrollmentContext";

function Header() {
  const { enrolledCourses } = useContext(EnrollmentContext);

  return (
    <header>
      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link>
        <Link to="/courses">Courses</Link>
        <Link to="/profile">Profile</Link>
      </nav>

      <h3>Enrolled: {enrolledCourses.length}</h3>
    </header>
  );
}

export default Header;
